name: Bug Report
title: "[Bug]: "
labels: bug
description: Report broken or incorrect behaviour
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug.
        Please note that this form is for bugs only!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: >
         A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: >
         If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Are you using the latest release ?
      description: >
        Older versions of the project may contain some bugs, That's why we release [newer versions](https://github.com/elebumm/RedditVideoMakerBot/releases/latest).
        
        (to avoid reporting a previously solved bug, try upgrading to the latest version or ask questions in our [discord server](https://discord.gg/swqtb7AsNQ).)
      options:
        - label: I'm using the latest release
          required: true
  - type: textarea
    attributes:
      label: System Information
      description: please fill your system informations
      value: >
        Operating System : [e.g. Windows 11]

        Python version : [e.g. Python 3.6]
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
